spring:
  application:
    name: piscinapp-core

  profiles:
    default: prod

  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: never
