server:
  forward-headers-strategy: framework

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    enabled: false

  swagger-ui:
    enabled: false

piscinapp:
  security:
    issuer: ${PISCINAPP_SECURITY_ISSUER}

    jwt:
      key-store-base64: ${JWT_KEYSTORE_BASE64}
      key-store-password: ${JWT_KEYSTORE_PASSWORD}
      key-password: ${JWT_KEY_PASSWORD}
      key-alias: ${JWT_KEY_ALIAS}
      key-id: ${JWT_KEY_ID}

    oauth2:
      access-token-time-to-live: ${PISCINAPP_ACCESS_TOKEN_TTL:15m}

      clients:
        validation:
          enabled: ${PISCINAPP_VALIDATION_CLIENT_ENABLED:false}
          client-id: ${PISCINAPP_VALIDATION_CLIENT_ID:piscinapp-validation}
          redirect-uri: ${PISCINAPP_VALIDATION_CLIENT_REDIRECT_URI:}
          scopes:
            - openid
            - profile
