spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/piscinappdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true

piscinapp:
  security:
    issuer: ${PISCINAPP_SECURITY_ISSUER:http://localhost:8080}