package com.rndymi.es.piscinapp.core.platform.web;

public enum ApiErrorCode {

    VALIDATION_ERROR,

    IDENTITY_USER_NOT_FOUND,

    IDENTITY_USERNAME_CONFLICT,

    IDENTITY_INVALID_CURRENT_PASSWORD,

    IDENTITY_LAST_ADMIN_CONFLICT,

    EMPLOYEE_NOT_FOUND,

    EMPLOYEE_ACCOUNT_CONFLICT,

    POOL_NOT_FOUND,

    MAINTENANCE_ACTIVITY_NOT_FOUND,

    POOL_MAINTENANCE_ACTIVITY_CONFLICT,

    CREW_NOT_FOUND,

    CREW_MEMBER_NOT_FOUND,

    CREW_MEMBERSHIP_CONFLICT,

    CREW_SUPERVISOR_CONFLICT,

    VISIT_NOT_FOUND,

    VISIT_STATE_CONFLICT,

    VISIT_CREW_NOT_ASSIGNABLE,

    VISIT_ACTIVITY_NOT_APPLICABLE,

    VISIT_INVALID_SCHEDULE,

    RESOURCE_INACTIVE,

    ACCESS_DENIED,

    AUTHENTICATION_REQUIRED
}
